import { spawnSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, realpathSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { prepareStaff, seedNote, specialistInstructions, staff, tomlString } from "./staff.ts";
import { assertPrivatePath, safeDirectory, safeWrite } from "./private-files.ts";

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const engineering = process.argv[2] === "dev";
const argv = process.argv.slice(3);
const briefs = ["war-room", "recap", "lineup", "daily"];
const usage = engineering ? 'Usage: ff-dev [ask "task"]' : 'Usage: ff-gm [ask "question" | brief <war-room|recap|lineup|daily> | specialist <research_boy|dynasty_knower|league_watcher|rookie_scout|ai_guru> "task" | staff]';
const within = (parent: string, child: string) => { const rel = relative(parent, child); return rel === "" || (!rel.startsWith("../") && rel !== ".." && !isAbsolute(rel)); };

function main(): number {
  if (argv[0] === "--help" || argv[0] === "help") { console.log(usage); return 0; }
  if (!engineering && argv[0] === "staff" && argv.length === 1) {
    for (const role of staff) console.log(`${role.name}: ${role.description}`);
    console.log("software_dev: separate engineering session via ff-dev");
    return 0;
  }
  let prompt: string | undefined;
  let label = "";
  let role: typeof staff[number] | undefined;
  if (argv.length === 0) { /* Interactive. */ }
  else if (argv[0] === "ask" && argv.length === 2 && argv[1]?.trim()) prompt = argv[1];
  else if (!engineering && argv[0] === "brief" && argv.length === 2 && briefs.includes(argv[1]!)) {
    prompt = readFileSync(join(repo, "gm/briefs", `${argv[1]}.md`), "utf8");
    label = `-${argv[1]}`;
  } else if (!engineering && argv[0] === "specialist" && argv.length === 3 && argv[2]?.trim()) {
    role = staff.find((entry) => entry.name === argv[1]);
    if (!role) { console.error(usage); return 2; }
    prompt = argv[2]; label = `-${role.name}`;
  } else { console.error(usage); return 2; }

  const requestedPrivate = resolve(process.env.FF_PRIVATE_DIR || join(repo, "private"));
  mkdirSync(requestedPrivate, { recursive: true });
  const privateDir = realpathSync(requestedPrivate);
  if (within(privateDir, repo) || (within(repo, privateDir) && !within(join(repo, "private"), privateDir))) {
    throw new Error("FF_PRIVATE_DIR must be private/ or outside the engineering repository, and cannot contain it.");
  }
  // This granted cache root must not become source access through a symlink.
  safeDirectory(join(repo, ".local"));
  safeDirectory(join(repo, ".local/cache"));
  const env = { ...process.env, FF_PRIVATE_DIR: privateDir, FF_CACHE_DIR: join(repo, ".local/cache"), FF_REPO_DIR: repo, PATH: `${join(repo, "bin")}:${process.env.PATH || ""}` };
  if (!engineering) {
    for (const file of ["LEAGUE_CONSTITUTION.md", "context.json"]) assertPrivatePath(join(privateDir, file), false);
    const validation = spawnSync("ff", ["context"], { env, stdio: ["ignore", "ignore", "inherit"] });
    if (validation.status !== 0 || validation.error) {
      console.error("GM not started: league validation failed (details above)."); return 1;
    }
  }
  for (const path of ["notes", "reports"]) safeDirectory(join(privateDir, path));
  if (!existsSync(join(privateDir, ".git"))) {
    const git = spawnSync("git", ["-C", privateDir, "init", "-q"], { stdio: "inherit" });
    if (git.status !== 0 || git.error) throw new Error("Could not initialize the private repository.");
  }
  const overrides: string[] = [];
  if (engineering) {
    overrides.push("agents.enabled=false", `developer_instructions=${tomlString(readFileSync(join(repo, "gm/agents/software_dev.md"), "utf8"))}`);
    safeDirectory(join(privateDir, "reports/engineering"));
  } else {
    seedNote(privateDir, "strategy.md", "# Franchise strategy\n\nDirection (contend / retool / rebuild): _not yet set — ask the Owner._\n\n## Owner preferences and mandates\n");
    seedNote(privateDir, "managers.md", "# Manager notes\n\nKeep dated observations separate from inferred tendencies.\n");
    seedNote(privateDir, "recommendations.md", "# Recommendation log\n\nAppend-only. Date · constitution hash · recommendation · reasoning · confidence · Owner decision.\n");
    safeWrite(join(privateDir, "AGENTS.md"), `<!-- Generated by ff-gm from gm/CHARTER.md. -->\n\n${readFileSync(join(repo, "gm/CHARTER.md"), "utf8")}`);
    overrides.push(...prepareStaff(repo, privateDir));
    if (role) overrides.push("agents.enabled=false", `developer_instructions=${tomlString(specialistInstructions(repo, role.name))}`);
  }
  const common = [
    "--strict-config", "-C", engineering ? repo : privateDir,
    "-m", engineering ? (process.env.FF_DEV_MODEL || "gpt-6-sol") : (process.env.FF_GM_MODEL || "gpt-6-sol"),
    "-c", `model_reasoning_effort=${tomlString((engineering ? process.env.FF_DEV_EFFORT : process.env.FF_GM_EFFORT) || "high")}`,
    "-c", 'web_search="live"', "-s", "workspace-write",
    "-c", `approval_policy=${tomlString(engineering ? "on-request" : "never")}`,
    "-c", "sandbox_workspace_write.network_access=true", "--add-dir", join(repo, ".local"),
    ...overrides.flatMap((value) => ["-c", value]),
  ];
  if (engineering) common.push("--add-dir", privateDir);
  if (prompt === undefined) {
    const result = spawnSync("codex", common, { env, stdio: "inherit" });
    if (result.error) throw result.error;
    return result.status ?? 1;
  }
  const stamp = `${new Date().toISOString().replace(/[:.]/g, "-")}-${randomUUID().slice(0, 8)}${label}`;
  const outputDir = join(privateDir, engineering ? "reports/engineering" : "reports");
  const out = join(outputDir, `${stamp}.md`);
  const events = join(outputDir, `${stamp}.events.jsonl`);
  const fd = openSync(events, "wx", 0o600);
  let result;
  try {
    result = spawnSync("codex", ["exec", ...common, "--json", "-o", out, "--", prompt], { env, stdio: ["ignore", fd, "inherit"] });
  } finally { closeSync(fd); }
  if (result.error) throw result.error;
  if (result.status !== 0) { console.error(`Agent failed; events: ${events}`); return result.status ?? 1; }
  if (!existsSync(out) || !readFileSync(out, "utf8").trim()) {
    console.error(`Agent returned no final report; events: ${events}`); return 1;
  }
  console.log(readFileSync(out, "utf8").trimEnd());
  console.error(`Saved: ${out}\nEvents: ${events}`);
  return 0;
}
try { process.exitCode = main(); }
catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
